"""empty message

Revision ID: 3360b1ce4afd
Revises: f10d5f0d021f
Create Date: 2020-08-23 17:13:03.900521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3360b1ce4afd'
down_revision = 'f10d5f0d021f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('liked_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_post_likes_liked_user_user', type_='foreignkey')
        batch_op.drop_constraint('fk_post_likes_liked_post_post', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_likes_liked_user_id_user'), 'user', ['liked_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_post_likes_liked_post_id_post'), 'post', ['liked_post_id'], ['id'])
        batch_op.drop_column('liked_post')
        batch_op.drop_column('liked_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_user', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('liked_post', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_post_likes_liked_post_id_post'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_post_likes_liked_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_post_likes_liked_post_post', 'post', ['liked_post'], ['id'])
        batch_op.create_foreign_key('fk_post_likes_liked_user_user', 'user', ['liked_user'], ['id'])
        batch_op.drop_column('liked_user_id')
        batch_op.drop_column('liked_post_id')

    # ### end Alembic commands ###
