"""empty message

Revision ID: 496a282aaef7
Revises: 5fb48a255eaa
Create Date: 2020-08-18 01:43:30.791160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496a282aaef7'
down_revision = '5fb48a255eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_comment_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comment_post_id_post'), 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_post_id_post'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
