"""empty message

Revision ID: 5fb48a255eaa
Revises: bde2652322c6
Create Date: 2020-08-18 01:38:41.493757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb48a255eaa'
down_revision = 'bde2652322c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_post_idx_post', type_='foreignkey')
        batch_op.drop_constraint('fk_comment_user_idx_user', type_='foreignkey')
        batch_op.drop_column('post_idx')
        batch_op.drop_column('user_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_idx', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('post_idx', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_comment_user_idx_user', 'user', ['user_idx'], ['id'])
        batch_op.create_foreign_key('fk_comment_post_idx_post', 'post', ['post_idx'], ['id'])

    # ### end Alembic commands ###
