"""empty message

Revision ID: 83d0b18cf4ca
Revises: cead2bca841f
Create Date: 2020-08-22 04:04:20.494608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d0b18cf4ca'
down_revision = 'cead2bca841f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_comment_post_idx_post', type_='foreignkey')
        batch_op.drop_constraint('fk_comment_user_idx_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_post_id_post'), 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comment_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('post_idx')
        batch_op.drop_column('user_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_idx', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('post_idx', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_comment_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_user_idx_user', 'user', ['user_idx'], ['id'])
        batch_op.create_foreign_key('fk_comment_post_idx_post', 'post', ['post_idx'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
