"""empty message

Revision ID: cead2bca841f
Revises: 59e11efadedd
Create Date: 2020-08-22 04:02:04.449749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cead2bca841f'
down_revision = '59e11efadedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
