"""empty message

Revision ID: f10d5f0d021f
Revises: c0a086de0dce
Create Date: 2020-08-23 16:38:35.870905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10d5f0d021f'
down_revision = 'c0a086de0dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liked_user', sa.Integer(), nullable=True),
    sa.Column('liked_post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_post'], ['post.id'], name=op.f('fk_post_likes_liked_post_post')),
    sa.ForeignKeyConstraint(['liked_user'], ['user.id'], name=op.f('fk_post_likes_liked_user_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_likes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_likes')
    # ### end Alembic commands ###
